import {
  Merge, Scissors, FileDown, FileText, FileUp,
  Edit, Image, Droplets, RotateCw,
  Hash, ImagePlus, Layers
} from 'lucide-react'

export const tools = [
  {
    id: 'merge-pdf',
    name: 'Gabungkan PDF',
    description: 'Gabungkan beberapa file PDF menjadi satu',
    icon: Merge,
    color: 'bg-red-500',
    accept: '.pdf',
    multiple: true,
  },
  {
    id: 'split-pdf',
    name: 'Pisahkan PDF',
    description: 'Pisahkan halaman dari file PDF',
    icon: Scissors,
    color: 'bg-orange-500',
    accept: '.pdf',
    multiple: false,
  },
  {
    id: 'compress-pdf',
    name: 'Kompres PDF',
    description: 'Kurangi ukuran file PDF',
    icon: FileDown,
    color: 'bg-amber-500',
    accept: '.pdf',
    multiple: false,
  },
  {
    id: 'pdf-to-word',
    name: 'PDF ke Word',
    description: 'Konversi file PDF ke dokumen Word',
    icon: FileText,
    color: 'bg-blue-500',
    accept: '.pdf',
    multiple: false,
  },
  {
    id: 'word-to-pdf',
    name: 'Word ke PDF',
    description: 'Konversi dokumen Word ke PDF',
    icon: FileUp,
    color: 'bg-indigo-500',
    accept: '.docx',
    multiple: false,
  },
  {
    id: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Tambah teks dan gambar ke PDF',
    icon: Edit,
    color: 'bg-purple-500',
    accept: '.pdf',
    multiple: false,
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF ke JPG',
    description: 'Konversi halaman PDF ke gambar JPG',
    icon: Image,
    color: 'bg-pink-500',
    accept: '.pdf',
    multiple: false,
  },
  {
    id: 'watermark',
    name: 'Tanda Air',
    description: 'Tambah tanda air ke file PDF',
    icon: Droplets,
    color: 'bg-cyan-500',
    accept: '.pdf',
    multiple: false,
  },
  {
    id: 'rotate-pdf',
    name: 'Rotasi PDF',
    description: 'Putar halaman PDF sesuai keinginan',
    icon: RotateCw,
    color: 'bg-green-500',
    accept: '.pdf',
    multiple: false,
  },
  {
    id: 'page-numbers',
    name: 'Nomor Halaman',
    description: 'Tambah nomor halaman ke PDF',
    icon: Hash,
    color: 'bg-lime-600',
    accept: '.pdf',
    multiple: false,
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG ke PDF',
    description: 'Konversi gambar JPG/PNG ke PDF',
    icon: ImagePlus,
    color: 'bg-emerald-500',
    accept: '.jpg,.jpeg,.png',
    multiple: true,
  },
  {
    id: 'organize-pdf',
    name: 'Urutkan Halaman',
    description: 'Atur ulang urutan halaman PDF',
    icon: Layers,
    color: 'bg-rose-500',
    accept: '.pdf',
    multiple: false,
  },
]

export const getToolById = (id) => tools.find(t => t.id === id)
